### ISSUE TITLE
Error while trying to download a video from Facebook

### ISSUE THREAD

**Issue by iMrDJAi** [mskian/video-dl#19]
> HD Not avilable for this Video

I used the link provided on examples, I also tried another links and it didn't work.

**Comment by mskian** [comment]
try via localhost - proxies and servers are blocked by fb

**Comment by iMrDJAi** [comment]
> try via localhost - proxies and servers are blocked by fb

@mskian Thanks for the reply, I'll try it out!

**Comment by mhkeller** [comment]
I tried the example fb video link on localhost:4000 and got an error "Data Not Found"
